### ISSUE TITLE
[Question] LVM for VMs

### ISSUE THREAD

**Issue by Uumas** [nilsmeyer/ansible-debootstrap#24]
I have a volume group (vg0) on a vm host platform, which has all vm root partitions as volumes (/dev/vg0/testvm-root). The vm sees the volume as /dev/vda. I've been trying for a while now, but can't figure out a way to handle this with this role. Is it possible without modifying this too much or do I basically need to reimplement the handling of partitions?

**Comment by nilsmeyer** [comment]
Do you want to bootstrap the VM from the host system, without booting into a VM? I think this may be possible, you would specify the layout with the logical volume as underlying device, e.g.:
```
layout:
  - device: '/dev/vg0/testvm-root'
    partitions:
      - num: 1
        size: 1M
        type: ef02
      - num: 2
        size: 1022M
        type: 8300
      - num: 3
        type: 8300
```

What could be difficult is that the partition table may not be detected automatically (one would need to add a step to call `partprobe`) and perhaps the detection of device names is off - devices would probably be named /dev/maper/vg0-testvm--root--part1 etc.. I think I already wrote some code to better determine the device names when putting in nvme support.

Creating the fstab and finding the boot device should work already since it uses UUID. 

Does this help at all?

**Comment by Uumas** [comment]
I should have been clearer. Yes, bootstrapping from the host would be ideal. I don't want multiple partitions, just one with no partition table so the root partition would be just /dev/vg0/testvm-root (/dev/vda, not /dev/vda1 on the vm). I use direct kernel boot, so a bootloader isn't needed at all.

**Comment by nilsmeyer** [comment]
I see, that would require a few modification since I haven't thought about that particular use-case, so for example:
```
layout:
  - device: '/dev/vg0/testvm-root'
    fs: ext4
    mount: /
```

This doesn't work currently but shouldn't be too difficult to add.

**Comment by Uumas** [comment]
Would it be possible to implement it so that the lvm volume could be created automatically too, something like this maybe:
```
layout:
  - lvm:
      lv: "{{ vm_name }}-root"  
      vg: atlantis  
      size: 5G  
      mount: /  
      fs: ext4
```
This isn't a great syntax, but you get the point.
