### ISSUE TITLE
"cryptsetup" tool uses early then it is installed

### ISSUE THREAD

**Issue by mvk15** [nilsmeyer/ansible-debootstrap#32]
The first Ansible task in the file `encryption.yml` uses the command `cryptsetup --version` before it will be installed in the 3rd task:
``` yaml
---

- name: fetch cryptsetup version  <==========================
  command: "cryptsetup --version"
  changed_when: no
  register: _cryptsetup_version

- name: register version
  set_fact:
    cryptsetup_version: "{{ _cryptsetup_version.stdout[11:] }}"

- block:
  - name: install dependencies  <============================
    apt:
      name: "{{ dependencies.encryption }}"
      state: latest
      update_cache: no # skip cache check since we already ran apt
```
